# this is the minimal environment file to install the dependencies of AQUA-diagnostics, 
# it is not meant to be used directly but is used by github actions
# Create the environment:
# mamba env create -f min-environment.yml 
# or if you really want to use conda
# conda env create -f min-environment.yml

name: aqua-diagnostics
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10,<3.13
  - cdo>=2.5.0 
  - eccodes==2.41.0
  - esmpy
  - tempest-extremes